apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: {{ .Values.nameSpace }}
spec:
  acme:
    # The ACME server URL
    # server: https://acme-staging-v02.api.letsencrypt.org/directory  ... use staging for initial tests
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.leEmail }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    # Enable the DNS challenge provider
    # https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/
    solvers:
    - selector:
        dnsNames:
        - {{ .Values.cfDnsZone }}
      dns01:
        cloudflare:
          apiKeySecretRef:
            name: {{ .Values.cfSecretName }}
            key: {{ .Values.cfSecretKey }}
