apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cfSecretName }}
  namespace: {{ .Values.certManagerNamespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    dnsZone: "{{ .Values.cfDnsZone }}"
type: Opaque
stringData:
  {{ .Values.cfSecretKey }}: {{ .Values.cfToken }}
